# Generated by Django 3.2 on 2021-12-02 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20211202_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailing',
            name='forms_count',
            field=models.PositiveIntegerField(default=2, verbose_name='Количество форм'),
            preserve_default=False,
        ),
    ]
