# Generated by Django 3.2.6 on 2021-12-03 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_mailing_forms_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='mailing_link',
        ),
        migrations.RemoveField(
            model_name='user',
            name='screenshot_link',
        ),
        migrations.RemoveField(
            model_name='user',
            name='text',
        ),
        migrations.AddField(
            model_name='user',
            name='mailing',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='backend.mailing'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='profile',
            field=models.CharField(default='profile', max_length=1000),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='UserMailingForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mailing_link', models.URLField(verbose_name='Ссылка')),
                ('text', models.TextField(verbose_name='Текст')),
                ('screenshot_link', models.URLField(verbose_name='Скриншот')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forms', to='backend.user')),
            ],
        ),
    ]
