# Generated by Django 3.2.6 on 2021-12-03 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_auto_20211203_1855'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermailingform',
            name='screenshot_link',
        ),
        migrations.AddField(
            model_name='usermailingform',
            name='screenshot',
            field=models.ImageField(default='', upload_to='screenshots'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='mailing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.mailing', verbose_name='Рассылка'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile',
            field=models.CharField(max_length=1000, verbose_name='Профиль'),
        ),
    ]
