# Generated by Django 3.2.6 on 2021-12-06 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_usermailingform_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailing',
            name='mass',
            field=models.FileField(blank=True, null=True, upload_to='mass', verbose_name='Массовое добавление'),
        ),
        migrations.AlterField(
            model_name='usermailingform',
            name='completed',
            field=models.BooleanField(default=True, verbose_name='Выполнено'),
        ),
    ]
