# Generated by Django 3.2.6 on 2021-12-07 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_auto_20211206_0952'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.CharField(max_length=1000)),
            ],
        ),
        migrations.AlterField(
            model_name='mailing',
            name='title',
            field=models.CharField(max_length=255, unique=True, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='mailinglink',
            name='must_deleted',
            field=models.BooleanField(default=True, verbose_name='Должна ли удаляться?'),
        ),
    ]
